//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOCENTES.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int usuarioID { get; set; }
        public string nombres { get; set; }
        public string apellidopaterno { get; set; }
        public string apellidomaterno { get; set; }
        public string documento { get; set; }
        public string correo { get; set; }
        public string codigo { get; set; }
        public string password { get; set; }
    }
}
